AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  api1BBC17DA:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${StackTagName} Environment ${EnvironmentTagName}
        - ResourceName: triggerDeploy
      StageName: !Ref EnvironmentAPIGatewayStageName
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /test:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${functionBBD9C52E.Arn}/invocations
              responses: {}
          /prod:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${function35F9596B.Arn}/invocations
              responses: {}
          /staging:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${functionBBD9C52E.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
    Metadata:
      StackeryName: triggerDeploy
  function35F9596B:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-function35F9596B
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: handleDeploy
      CodeUri: src/handleDeploy
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          GITHUB_WEBHOOK_SECRET: !Ref EnvConfiggithubSecretAsString
          GITHUB_TOKEN: !Ref EnvConfiggithubTokenAsString
          STACKERY_KEY: !Ref EnvConfigstackeryKeyAsString
          STACKERY_SECRET: !Ref EnvConfigstackerySecretAsString
          STACKERY_ENV: !Ref EnvConfigstackeryEnvAsString
          STACKERY_USER_POOL_ID: !Ref EnvConfigstackeryUserPoolIdAsString
          STACKERY_USER_POOL_CLIENT_ID: !Ref EnvConfigstackeryUserPoolClientIdAsString
      Events:
        api1BBC17DAPOSTprod:
          Type: Api
          Properties:
            Path: /prod
            Method: POST
            RestApiId: !Ref api1BBC17DA
    Metadata:
      StackeryName: handleDeploy
  functionBBD9C52E:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-functionBBD9C52E
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: bashFunction
      CodeUri: src/bashFunction
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Layers:
        - arn:aws:lambda:us-west-2:744348701589:layer:bash:4
      Events:
        api1BBC17DAPOSTtest:
          Type: Api
          Properties:
            Path: /test
            Method: POST
            RestApiId: !Ref api1BBC17DA
        api1BBC17DAPOSTstaging:
          Type: Api
          Properties:
            Path: /staging
            Method: POST
            RestApiId: !Ref api1BBC17DA
    Metadata:
      StackeryName: bashFunction
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvironmentAPIGatewayStageName:
    Type: String
    Description: Environment name used for API Gateway Stage names (injected by Stackery at deployment time)
  EnvConfiggithubSecretAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/githubSecret
  EnvConfiggithubTokenAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/githubToken
  EnvConfigstackeryKeyAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/stackeryKey
  EnvConfigstackerySecretAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/stackerySecret
  EnvConfigstackeryEnvAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/stackeryEnv
  EnvConfigstackeryUserPoolIdAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/stackeryUserPoolId
  EnvConfigstackeryUserPoolClientIdAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/stackeryUserPoolClientId
Metadata:
  EnvConfigParameters:
    EnvConfiggithubSecretAsString: githubSecret
    EnvConfiggithubTokenAsString: githubToken
    EnvConfigstackeryKeyAsString: stackeryKey
    EnvConfigstackerySecretAsString: stackerySecret
    EnvConfigstackeryEnvAsString: stackeryEnv
    EnvConfigstackeryUserPoolIdAsString: stackeryUserPoolId
    EnvConfigstackeryUserPoolClientIdAsString: stackeryUserPoolClientId